# Site settings
title: Cody E. Clifton
email: # your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Cody E. Clifton is an experienced educator, organizer, and leader, 
  with a doctorate in mathematics and a broad technical skill set 
  involving programming and web development
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# usernames
flickr_username: cliftoce
github_username: cliftoce
youtube_username: cliftoce
google_username: codyeclifton
linkedin_username: codyeclifton

# Build settings
markdown: kramdown